### ISSUE TITLE
render issues

### ISSUE THREAD

**Issue by le1smo** [queensferryme/hugo-theme-texify#22]
Thanks for your pretty theme.

There is a render issue when use a different customer font in Safari and mobile.
<img width="693" alt="image" src="https://user-images.githubusercontent.com/76763517/166912379-920aa0a9-d46c-4bc8-ad7d-23d27d592319.png">

No problem in Chrome.

<img width="693" alt="image" src="https://user-images.githubusercontent.com/76763517/166912424-93f065f3-1632-4f2c-975b-7aa0483da700.png">

custom.css
```css
@import url('https://cdn.jsdelivr.net/npm/lxgw-wenkai-webfont@1.6.0/style.css');

#wrapper {
    font-family: 'LXGW WenKai', "Times New Roman", serif
}
```
