### ISSUE TITLE
Support for syntax highlighting

### ISSUE THREAD

**Issue by assayire** [queensferryme/hugo-theme-texify#26]
Does this theme support syntax highlighting in code blocks? If so, how do I enable it? Currently,  the code in code blocks are all just red color.

Thanks.

**Comment by queensferryme** [comment]
Hi, syntax highlighting works well for me (e.g. [blog](https://queensferry.me/post/julia-+-flux.jlgraphsage-%E4%B8%8E%E5%9B%BE%E7%A5%9E%E7%BB%8F%E7%BD%91%E7%BB%9C/)). Could you post your code blocks so that I can help identify the problem?

> Hint, maybe you should look at `config.toml`:
```toml
[markup.highlight]
style = "emacs" # syntax highlight style, see https://xyproto.github.io/splash/docs/
```

**Comment by assayire** [comment]
Ahh I see now.

Added this to turn on the magic. Works fine now.

```toml
[markup]
defaultMarkdownHandler = "goldmark"

[markup.goldmark.renderer]
unsafe = true # enable html in markdown

[markup.highlight]
style = "emacs"
```
