### ISSUE TITLE
Date format

### ISSUE THREAD

**Issue by emeralit** [queensferryme/hugo-theme-texify#7]
Hi,
can I change the date format in config.toml, as in other themes?
Thanks

**Comment by queensferryme** [comment]
Hi @emeralit, since 43015aa you can configure the date format in `config.toml` like this:
```toml
[params]
  # ...
  dateFormat = "2006-01-02"
```

Read https://gohugo.io/functions/format/ on more available date formats.

Let me know if you need any help!
